id = "fasterbasic"
name = "FasterBASIC"
description = "Syntax highlighting and language support for FasterBASIC"
version = "0.1.0"
schema_version = 1
authors = ["FasterBASIC Team"]
repository = "https://github.com/albanread/FasterBASIC"

[language_servers]

[grammars.fasterbasic]
repository = "https://github.com/albanread/FasterBASIC"
rev = "045b3e4c8e5f8b9e5e5e5e5e5e5e5e5e5e5e5e5e"
path = "fasterbasic-zed/grammars/fasterbasic"
